name: registrar usuario

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut codigo
        uses: actions/CheckOut@v4

      - name: Instalar k6
        run: |
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y
      - name: ejecutar archivo de registrarUsuario
        run: k6 run registrarUsuario.js

      - name: Subir reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-reporte
          path: reporte/*.html
