name: registrar usuario

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut codigo
        uses: actions/CheckOut@v4

      - name: Instalar k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D68
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6 -y
      - name: ejecutar archivo de registrarUsuario
        run: k6 run registrarUsuario.js
